### PR TITLE
Prevent expansion in Move After Next Sibling

### PR DESCRIPTION
**Pull request by spinda**
Given the following original state:

Original

Executing "Move After Next Sibling" on tab `A` would result in the following state, unintentionally expanding collapsed tree `B`:

Old Result

This patch avoids that unintentional expansion, resulting in the following state instead:

New Result

### CODE REVIEW

**Comment by piroor** [comment]
Thanks! But I think that listening of notification messages from TST looks unnecessary. As another approach, how about moving the target tab to the position "previous of the next-next sibling"? For example, assume that there are four tabs:

* A (target tab)
* B (next sibling)
  * C
* D (next-next sibling)

Then calling `move-before` for the tab A with the reference tab D, it will produce a result:

* B
  * C
* A (target tab, moved)
* D

In this case the sub tree under the tab B won't be expanded. If the tab A is a root level tab and there is no next-next sibling, you'll just need to call `move-to-end` instead.

**Comment by piroor** [comment]
There looks to two methods how to get the ID of next-next.

* Multiple `get-tree` API calls: getting the next sibling with the keyword `nextSibling`, then do that again for the got next sibling.
* Single `get-tree` API call: getting the tree information of the parent tab with the keyword `parent`, then traverse the `children` of the result.

However just the first method looks enough to do the thing, because the second method will fail if the target tab is a root level tab, (then you'll need to fall back to the first method anyway).

**Comment by spinda** [comment]
> Multiple `get-tree` API calls: getting the next sibling with the keyword `nextSibling`, then do that again for the got next sibling.

Am I missing something, or does that only work to get the next sibling of the active tab? (relevant TST code: https://github.com/piroor/treestyletab/blob/c82ef55548b16a1fa641c3c146a6ede884fffdde/webextensions/common/tst-api.js#L1135-L1136)

**Comment by piroor** [comment]
Oops, you are right! I completely misunderstood the API design I did... Only the second approach I wrote (traversing of the tree under the parent tab, otherwise traversing all root level tabs) looks effective.

Anyway, something new special keyword to get next/previous sibling for an arbitrary tab via the `get-tree` API looks useful. I'll add it at the next release of TST.

**Comment by piroor** [comment]
I've added `-of-<id>` suffixed patterns.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#basics-to-specify-tabs

**Comment by spinda** [comment]
Fantastic, these are really useful!

I think there's just one more scenario to consider. Say the tree structure looks like this:

- tab A
  - tab B (target tab)
  - tab C (next sibling)
    - tab D
      - tab E
- tab F

There's no next-next sibling for tab B, and `move-to-end` won't work as that would move tab B all the way after tab F (unless there were some way to, say, `move-to-last-child` of tab A).

One potential solution: after seeing there's no `nextSibling` for tab C, walk tab C's `get-tree` data to find its last recursive child (tab E), and retrieve the ID of `next-of-E` (tab F). Then move tab B before tab F. Would this retain tab B's indentation level, or would tab B end up at the same indentation level as tab F after the move?

**Comment by piroor** [comment]
> Would this retain tab B's indentation level, or would tab B end up at the same indentation level as tab F after the move?

In this case, both request will keep the tab B as a child of A. TST fixes the tree structure only when the structure produced after the moved tab is invalid (for example, a moved child tab appeared in the middle of another tree).

We get the last descendant of a tree frequently, thus I think one more alias like `lastdescendant-of-<id>` will help such cases.

**Comment by piroor** [comment]
`lastDescendant-of-<id>` is now available with the commit https://github.com/piroor/treestyletab/commit/9ae8740d024b3a27822d7789f3ef80ff1c86cc08 .

**Comment by spinda** [comment]
Awesome! I'll incorporate these into the changeset here.

**Comment by spinda** [comment]
Updated!

> In this case, both request will keep the tab B as a child of A. TST fixes the tree structure only when the structure produced after the moved tab is invalid (for example, a moved child tab appeared in the middle of another tree).

This doesn't seem to be the case after all: when I tried it, `move-before` made the tab match the indentation level of the reference tab, and `move-to-end` made the tab a root tab. So I tacked on a small post-processing step to fix the indent after the move in these cases.

**Comment by piroor** [comment]
I'm very sorry I forgot to merge this before the latest version was released. I'll release a new version including this soon.

**Pull request merged**
